version: '1.0'
services:
  microservice-prices:
    image: microservice-prices:v1
    container_name: microservice-prices
    expose: 
      - '8095'
    ports:
      - '8095:8095'
    restart: always
    networks:
      - networkcloud


  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    ports:
      - "9000:9000"
    networks:
      - networkcloud
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://sonarqube-db:5432/sonar
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar

  sonarqube-db:
    image: postgres:latest
    container_name: sonarqube-db
    networks:
      - networkcloud
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    restart: always

networks:
  networkcloud:
    driver: "bridge"
